version: '3'
services:
  backend_api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8080

  front:
    build:
      context: ./frontend
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on: 
      - backend_api
